title: Confuror 2019
email: vidafur.reg@gmail.com
description:
  en: >-
    Confuror is a furry convention based in Mexico, hosted in the city of Guadalajara, Jalisco.
    Is the annual main event supported by the furry local comunity Vidafur. It's comming in 2019 with its second edition held in October 11, 12 and 13 at Fiesta Americana Guadalajara Hotel.
  es: >-
    Confuror es una convención furry con sede en México, realizandose en la ciudad de Guadalajara, Jalisco.
    Es el evento anual realizado por la comunidad furry de Vidafur. Regresa en 2019 con su segunda edición el 11, 12 y 13 de Octubre en el hotel Fiesta Americana Guadalajara.
edition_label:
  en: October 11, 12 & 13 2019 | Guadalajara, México
  es: 11, 12 y 13 de Octubre 2019 | Guadalajara, México
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
version: 2.1.0

sass:
  load_paths:
    - _sass
    - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - .bundle
  - vendor
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - .gitignore
