title: Confuror 2018
email: vidafur.reg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Confuror is a furry convention based in Mexico, hosted in the city of Guadalajara, Jalisco.
  Is the annual main event supported by the furry local comunity Vidafur. "The howling gala" is 2018 theme, and will be held in October 12, 13 and 14 at Laffayette Hotel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

sass:
  load_paths:
    - _sass
    - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - .bundle
  - vendor
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - .gitignore
