title: Confuror 2022
email: info@confuror.org
description:
  en: >-
    Confuror is a furry convention based in Mexico, hosted in the city of Guadalajara, Jalisco.
    Is the annual main event supported by the furry local comunity Vidafur. It's comming back this 2022 with it's fifth edition in October 20 - 23.
  es: >-
    Confuror es una convención furry con sede en Guadalajara Jalisco, México; organizado por la comunidad furry de Vidafur de forma anual. Llega en 2022 con su quinta edición del 20 al 23 de Octubre.
edition_label:
  en: October 20 - 23 2022 | Guadalajara, México
  es: 20 - 23 de Octubre 2022 | Guadalajara, México
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
version: 5.0.3

# Sass configuration
sass:
  load_paths:
    - _sass
    - node_modules

# Collections
collections:
  pages:
    output: true
  posts:
    output: true

# Format templates
formats:
  featured_paragraph: components/featured-paragraph.html
  cta_button: components/cta-button.html
  inline_alert: components/alert.html
  inline_faq: components/inline-faq.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - .bundle
  - vendor
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - .gitignore
